---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kube-vip/ks.yaml
  - ./intel-device-plugin/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./nvidia-device-plugin/ks.yaml
  - ./reloader/ks.yaml
