---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./external-dns.yaml
  - ./gitea.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./nvidia.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
