---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mvisonneau-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://charts.visonneau.fr
  timeout: 3m
