---
- hosts:
    # TODO
    # - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
    - name: Ensure group "kah" exists with correct gid
      group:
        name: kah
        state: present
        gid: 568

    - name: Create kah user
      user:
        name: kah
        comment: k8s at home
        uid: 568
        group: kah

    - name: Ensure nfs and open-iscsi
      apt:
        pkg:
          - open-iscsi
          - nfs-common

    - name: Setup storage disks
      block:
        - name: Create a new ext4 primary partition
          parted:
            device: /dev/nvme0n1
            number: 1
            state: present
            fs_type: ext4
        - name: Create a ext4 filesystem on /dev/nvme0n1
          filesystem:
            fstype: ext4
            dev: /dev/nvme0n1
        - name: Mount Disk to /data
          mount:
            path: /data
            src: /dev/nvme0n1p1
            fstype: ext4
            state: mounted
        - name: Give kah ownership
          file:
            path: /data
            owner: kah
            group: kah
            recurse: yes
            # mode: '1777'
