---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 192.168.1.150-192.168.1.160
  METALLB_K8S_GATEWAY_ADDR: 192.168.1.150
  METALLB_INGRESS_ADDR: 192.168.1.151
  #
  NAS_ADDR: '192.168.1.101'
  #
  NETWORK_K8S_CLUSTER_CIDR: '10.42.0.0/16'
  NETWORK_K8S_SERVICE_CIDR: '10.43.0.0/16'
  NETWORK_MANAGEMENT_CIDR: '192.168.1.0/16'
  VPN_GATEWAY_VPN_PORT: '51820'
  VPN_FORWARDED_PORT_1: '56059'
  #
  SVC_HOME_ASSISTANT_ADDR: '192.168.1.152'
  SVC_MOSQUITTO_ADDR: '192.168.1.153'
  SVC_JELLYFIN_ADDR: '192.168.1.154'
  SVC_GROCY_ADDR: '192.168.1.155'
  SVC_BLOCKY_ADDR: '192.168.1.156'
  SVC_QBITTORRENT_ADDRESS: '192.168.1.157'
