---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - bazarr
  - lidarr
  - prowlarr
  - qbittorrent
  - radarr
  - readarr
  - sonarr
  - youtubedl-material
